apiVersion: v1
kind: Pod
metadata:
  name: rbac-test-pod
  namespace: foundations
spec:
  serviceAccountName: readonly-sa
  containers:
  - name: kubectl-container
    image: bitnami/kubectl:latest
    command: ["/bin/sh", "-c", "sleep 3600"]