apiVersion: v1
kind: Service
metadata:
  name: nginx-internal-svc
  namespace: foundations
spec:
  type: ClusterIP
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80