apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-ebs-claim
  namespace: foundations
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 5Gi